version: 2.1

jobs:
  checkoutAndTest:
    machine: true
    steps:
      - run: "echo === Checkout and Test ==="
      - run: "npm install"
      - run: "npm test"
  integrateFrontend:
    machine: true
    steps:
      - run: "echo === Integrate Frontend ==="
      - run: "echo clone repos"
      - run: "git clone https://github.com/BrendanDB/3w5-h22-tp2-backend.git"
      - run: "git clone https://github.com/BrendanDB/3w5-h22-tp2-frontend.git"
      - run: "cd ./3w5-h22-tp2-frontend && npm install && npm build"
      - run: "mkdir ./3w5-h22-tp2-backend/public"
      - run: "cp -rT ././3w5-h22-tp2-frontend/build ./3w5-h22-tp2-backend/public"
  deploy:
    machine: true
    steps:
      - run: "echo === Deployment ==="
      - run: "cd ./3w5-h22-tp2-backend && ls -Rl"
workflows:
  build:
    jobs:
      - checkoutAndTest
      - integrateFrontend:
          requires:
            - checkoutAndTest
      - deploy:
          requires:
            - integrateFrontend