version: 2.1

jobs:
  checkoutAndTest:
    machine: true
    steps:
      - run: "echo test"
  integrateFrontend:
    machine: true
    steps:
      - run: "echo integrate"
  deploy:
    machine: true
    steps:
      - run: "echo deploy"
workflows:
  build:
    jobs:
      - checkoutAndTest