version: 2.1

jobs:
  checkoutAndTest:
    machine: true
    steps:
      - run: "echo checkoutAndTest"
      - run: "cd .."
      - run: "npm install"
      - run: "npm test"
  integrateFrontend:
    machine: true
    steps:
      - run: "echo integrate"
  deploy:
    machine: true
    steps:
      - run: "echo deploy"
workflows:
  build:
    jobs:
      - checkoutAndTest
      - integrateFrontend:
          requires:
            - checkoutAndTest
      - deploy:
          requires:
            - integrateFrontend